apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-netflix
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-netflix
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: 30080
