replicaCount: 2

image:
  repository: oussama132/netflix-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

container:
  port: 80

resources: {}
